# Generated by Django 6.0.4 on 2026-04-21 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_customer_invoice_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='ammount',
            new_name='amount',
        ),
    ]
