# Generated by Django 6.0.4 on 2026-04-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_rename_ammount_invoice_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zoho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acess_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('organization_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
