# Generated by Django 6.0.4 on 2026-04-21 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_zoho'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Zoho',
            new_name='ZohoToken',
        ),
    ]
