# Generated by Django 6.0.4 on 2026-04-21 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_rename_zoho_zohotoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zohotoken',
            old_name='acess_token',
            new_name='access_token',
        ),
    ]
