# Generated by Django 6.0.4 on 2026-05-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_ingredient_menuitem_deliveryorder_menuingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='zoho_contact_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='zoho_pricebook_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
