# Generated by Django 6.0.4 on 2026-05-05 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_customer_zoho_contact_id_customer_zoho_pricebook_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='GeneratedInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoho_invoice_id', models.CharField(max_length=100)),
                ('invoice_number', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.customer')),
                ('delivery_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_invoices', to='invoices.deliveryorder')),
            ],
            options={
                'unique_together': {('delivery_order', 'customer')},
            },
        ),
    ]
