# Generated by Django 6.0.4 on 2026-05-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_customer_rate_generatedinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='BSB',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='account',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
