# Generated by Django 6.0.4 on 2026-05-06 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_alter_customer_bsb_alter_customer_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SleeveInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sleeve_inventory', to='invoices.menuitem')),
            ],
        ),
    ]
