# Generated by Django 6.0.4 on 2026-05-07 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0013_deliveryorder_is_delivered_sleeveinventory"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="deliveryitem",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="deliveryitem",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="invoices.customer",
            ),
        ),
        migrations.CreateModel(
            name="CustomDeliveryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "delivery_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_entries",
                        to="invoices.deliveryorder",
                    ),
                ),
            ],
            options={
                "unique_together": {("delivery_order", "name")},
            },
        ),
        migrations.AddField(
            model_name="deliveryitem",
            name="custom_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="invoices.customdeliveryentry",
            ),
        ),
    ]
