# Generated by Django 6.0.4 on 2026-06-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_alter_deliveryitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='customer_order',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
